apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spring-petclinic
resources:
- ../../base
images:
- name: harbor.tanzu.frankcarta.com/apps/spring-petclinic-application
  digest: sha256:e918f67f22b6a283a7ad8e1d15cf16ba1ce71c108b0e78e064c83992198434ae
