apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spring-petclinic
resources:
- ../../base
images:
- name: harbor.tanzu.frankcarta.com/apps/spring-petclinic-application
  digest: sha256:32e30d042357f3d4b1d44c417c6a1b9eb79e303a29fd0c60a4a942e81000f1fe
